version: "3.9"
services:
  web:
    image: nginx:alpine
    ports:
      - "5555:80"
    volumes:
      - ./app:/var/www/html
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./app
    volumes:
      - ./app:/var/www/html
    env_file: .env
    environment:
      APP_ENV: production

  db:
    image: mariadb:11
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root_change_me}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine

  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - kuma_data:/app/data
    ports:
      - "3001:3001"

volumes:
  db_data:
  kuma_data:
